import {IAnimeItem} from "../Interfaces/IAnimeItem";

export const animeData: IAnimeItem[] = [
    //1
    {
        id: 1,
        title: "Chainsaw man",
        description: "Denji has to completely change his life in order to work off his father's exorbitant debts. He becomes a Yakuza henchman in the difficult task of destroying demons. Now Denji has only one goal – money, only in them he sees a chance for liberation. Wanting to make a profit faster, the guy forgets about caution and dies in one of the fights. Faithful Pochito saves the owner by merging with him and giving him the ability to partially transform into a chainsaw.",
        genre: ["", "Demons", "Adventures", "Supernatural", "Senen", "Action"],
        rate: 9.9,
        age: "18+",
        year: 2022,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/6319cd947a99a365246749.jpg",
        linkVideo: "https://www.youtube.com/embed/dFlDRhvM4L0",
    },
    //2
    {
        id: 2,
        title: "Spy x Family Part 2",
        description: "Lloyd Forger hides that he is a secret agent of Vestalis. Yor Forger keeps silent that he is an assassin working in the Uprising. Nevertheless, the truth about their fictitious marriage and real professions is known to Loyd's \"daughter\", Anya, whom he took from the orphanage, unaware that she is not as simple as it seems. A girl who has gone through experiments has gained the ability to read other people's thoughts. The example of this fake family confirms that there is a lie for salvation. Especially when nothing less is at stake — world peace and the lives of innocent people!",
        genre: ["", "Comedy", "Senen", "Action"],
        rate: 9.6,
        age: "0+",
        year: 2022,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/631cbcdda8fae239603812.jpg",
        linkVideo: "https://www.youtube.com/embed/dkgOtUWicOs",
    },
    //3
    {
        id: 3,
        title: "Blue Lock",
        description: "The promising forward of the Saga Thread, who failed to properly dispose of the ball in the final of the youth tournament, also gets into the project. Will Isagi be able to cast aside empty doubts and prove to everyone his genius, efficiency, and game maturity? To become a world-class striker, you first need to survive in the \"Blue Prison\" and earn the favor of the Dzimpati Ego. And sagas will have to put aside all doubts and build a bridge to the cherished dream by force. The main thing is not to break down halfway. The young striker is no stranger to heavy loads, but does Isagi have enough tactical training and endurance to correctly build a strategy for the entire period of passing the \"Blue Prison\"?",
        genre: ["", "Senen", "Sport"],
        rate: 9.6,
        age: "14+",
        year: 2022,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/6341d35f1734f259446412.jpg",
        linkVideo: "https://www.youtube.com/embed/8BD8vyNpvMo",
    },
    //4
    {
        id: 4,
        title: "The Eminence in Shadow",
        description: "In our world, it's hard to pull this off, because no matter what you do, you can't trample on an atomic bomb. And so, thinking about ways to repel nuclear weapons with bare hands, our hero comes to the conclusion that there is no way without magic. It turned out conveniently, because soon after that the guy met the notorious truck, which sent him to the next world, or to be more precise, to a world full of swords, magic and other delights of fantasy universes. Now Sid will have no obstacles on the way to becoming the greatest ruler from the shadows.",
        genre: ["", "Comedy", "Fantasy", "Action"],
        rate: 9.4,
        age: "16+",
        year: 2022,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/6319d10357dec953113094.jpg",
        linkVideo: "https://www.youtube.com/embed/JExp_Mafxgc",
    },
    //5
    {
        id: 5,
        title: "Sword Art Online: Progressive Movie - Hoshi Naki Yoru no Aria",
        description: "Asuna Yuki was the best student, diligently preparing for the entrance exams to high school, but that was before she borrowed a virtual reality gaming system from her brother and found herself trapped in Sword Art Online along with ten thousand other frightened players. Time passes, and Asuna begins to fear what will become of her life outside of the fantasy world. What a loser she can be in the eyes of her peers and parents. Not wanting to wait on the sidelines while more experienced players complete the game, Asuna uses her learning abilities to learn the mechanics of the game and swordsmanship.",
        genre: ["", "Adventures", "Fantasy", "Action"],
        rate: 9.5,
        age: "16+",
        year: 2022,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/62cf3120e5fe2978650321.jpg",
        linkVideo: "https://www.youtube.com/embed/C3O6RhPsCTM",
    },
    //6
    {
        id: 6,
        title: "Date a live",
        description: "The population of the Earth is in danger - alien creatures decide to attack humanity. People are already used to the fact that in addition to the standard storms, storms and tsunamis, now there will also be problems with the weather, harvest and air temperature. Terrible troubles cannot be stopped by high-class weapons or conversations with opponents. Is it worth risking your life to calm a terrible tornado that comes for the third time in a day for ten minutes? Why run with a sword at the ready into the abyss of events when you can make everything more cunning?",
        genre: ["", "Comedy", "Fantasy", "Action"],
        rate: 9.3,
        age: "16+",
        year: 2013,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5c3795f58c297270015274.jpg",
        linkVideo: "https://www.youtube.com/embed/6GW0wXMt2CQ",
    },
    //7
    {
        id: 7,
        title: "Angel Beats!",
        description: "Otonashi wakes up after a long sleep, only to find out that he is dead. A girl with a rifle named Yuri explains to him that they are in the afterlife, and Otonashi realizes that the only thing he can remember about himself is his name. Yuri tells him that she leads the \"Front of the Underworld\" and is waging a war against a girl named Tenshi. Unable to believe it, Otonashi tries to talk to her, but the meeting does not go as he would like.",
        genre: ["", "Harem", "Comedy", "Furs", "Romance", "Fantasy", "School"],
        rate: 6.0,
        age: "16+",
        year: 2010,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/60b490dda5b48793747490.jpg",
        linkVideo: "https://www.youtube.com/embed/Turf7WDB3iY",
    },
    //8
    {
        id: 8,
        title: "Absolute Duo",
        description: "Tooru Kokonoe hopes to enter this academy in order to gain strength and avenge the murder of his sister and friends. However, at the opening ceremony, he learns that he is forced to fight against the person sitting next to him, and the loser is expelled. Also, following the rules established at the academy, Toru gets Julia Sigtuna as a partner, with whom he now has to study and work in a team until graduation. Where is there before making plans for revenge, when there is such a silver-haired beauty nearby...",
        genre: ["", "Harem", "Romance", "Supernatural", "School", "Action", "Etty"],
        rate: 6.7,
        age: "16+",
        year: 2015,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5d63d4ff1dcd9520316178.jpg",
        linkVideo: "https://www.youtube.com/embed/1CBctbw3c0s",
    },
    //9
    {
        id: 9,
        title: "Engage Kiss",
        description: "Veyron City is a city on a huge floating island in the Pacific Ocean that does not belong to any country. Thanks to the extraction of orgonium, a new source of energy, it is in the center of world attention. And there are so-called \"D—disasters\" - incidents caused by devils. Few people know about D-disasters, including PMCs who are engaged in their elimination. In one of these companies, the tiniest, works with yu. For some reason, he chooses errands very meticulously, so he always has problems with money. Xiu is rescued by the ex-girlfriend and daughter of Ayano's former boss, as well as Kisara, with whom he is connected by dangerous ties...",
        genre: ["", "Demons", "Comedy", "Romance"],
        rate: 9.4,
        age: "16+",
        year: 2022,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/630914b08c91d247771532.jpg",
        linkVideo: "https://www.youtube.com/embed/9Dx4Ml1eBKM",
    },
    //10
    {
        id: 10,
        title: "Assassins Pride",
        description: "In a world where only the nobility owns me and leads the battle with the creatures of darkness, the lack of abilities puts young Merida in a dangerous position. Under the pretext of training, the ruthless killer Kufa must evaluate the girl's skills and determine whether she is the true heir of the Angel family. If she does not live up to expectations, another plan will be used, the result of which is her death..",
        genre: ["", "Fantasy"],
        rate: 8.2,
        age: "14+",
        year: 2019,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5d9f5a769cc2f209060036.jpg",
        linkVideo: "https://www.youtube.com/embed/RLhRH1txge0",
    },
    //11
    {
        id: 11,
        title: "The Future Diary",
        description: "Yukiteru Amano is a simple fourteen-year-old boy studying at school. He was used to constantly doing everything on his own and tried to achieve heights all his conscious life. But it turns out that he is quite closed and is not going to change. Such a lifestyle suits him completely, and he is insanely glad that this is happening. The only one he communicates with is a fictional friend named Deus. He is the God of the universe and constantly helps the hero cope with various difficulties.",
        genre: ["", "Detective", "Psychological", "Supernatural", "Senen", "Thriller", "Action"],
        rate: 7.9,
        age: "18+",
        year: 2011,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5a85b5326b196703926212.jpg",
        linkVideo: "https://www.youtube.com/embed/LLDA9cfRLlg",
    },
    //12
    {
        id: 12,
        title: "Peach Boy Riverside",
        description: "Once upon a time, in ancient times, an old man and an old woman lived in distant lands. The old man was gathering firewood in the mountains, and the old woman was washing clothes in the river. We skip part of it. In the end, the demon was defeated. But there are enough of his kind in the world, and therefore Momotaro set sail. The terrible monster was defeated and only one thing overshadowed the joy of victory… The winner was glowing with pleasure. Let's assume... what if the waves brought far more than one peach? What if that peach was just one of many others like it?",
        genre: ["", "Senen", "Fantasy"],
        rate: 7.2,
        age: "18+",
        year: 2021,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/60d857bfdaf53483045798.jpg",
        linkVideo: "https://www.youtube.com/embed/zlhqLdmn9dw",
    },
    //13
    {
        id: 13,
        title: "Classroom of the Elite",
        description: "Kedo Ikusei is a famous educational institution that trains incredibly talented children who are able to become true masters in their field of activity in the future. The Academy has outstanding performance. Competing institutions definitely cannot boast of one hundred percent employment of students who immediately after completing the course receive prestigious jobs. All high school students here are not constrained by serious rules and strict discipline. They themselves understand the value of studying, so they try not to be distracted by stupid entertainment.",
        genre: ["", "Drama", "Slice of life", "Psychological", "School"],
        rate: 9.6,
        age: "14+",
        year: 2017,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5ab171c6da42c160184249.jpg",
        linkVideo: "https://www.youtube.com/embed/hsfBOwAIhOw",
    },
    //14
    {
        id: 14,
        title: "Magical Girl Site",
        description: "Every person who is faced with bullying dreams of one day taking revenge on a vile abuser. Aya Asagiri is a fourteen–year-old person who is pretty tired of constant ridicule. The girl does not find peace either in her home walls, where her brash brother is waiting for her, or at school, where cruel classmates are always pestering her. At a certain point, the main character begins to think about suicide. Suddenly, she comes across a rather interesting site. On it, an inquisitive visitor receives a magic wand and turns into a real sorceress.",
        genre: ["", "Drama", "Psychological", "Supernatural", "Horrors"],
        rate: 9.0,
        age: "16+",
        year: 2018,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5abe33ee6e805560704181.jpg",
        linkVideo: "https://www.youtube.com/embed/fdgZqVh6yYs",
    },
    //15
    {
        id: 15,
        title: "Akame Ga Kill!",
        description: "Tatsumi once went together with his close friends to the metropolis to earn money and save his native village from poverty. From an early age, he trained, so he was not a beginner in the field of fighting and could easily deal with any opponent. But, once inside a huge city, the main character was not only subjected to a cruel deception by one beauty, but also lost all his savings. Tatsumi decided to join the city army. He wanted to be reincarnated as a captain, but the local leader threw the ambitious boy away and explained that it was impossible to act like that.",
        genre: ["", "Drama", "Adventures", "Senen", "Fantasy", "Action"],
        rate: 9.0,
        age: "16+",
        year: 2014,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/60be739524217975343574.jpg",
        linkVideo: "https://www.youtube.com/embed/mAzFWd5WqOg",
    },
    //16
    {
        id: 16,
        title: "So I'm a Spider, So What?",
        description: "I, the main character, was an ordinary schoolgirl, but suddenly I was reborn into a spider monster in another world. Yes, and I found myself in a dungeon full of monsters. Armed only with ingenuity and boundless optimism, I have to defeat monsters much stronger than myself with the help of traps from the web... So begins the story of the survival of a very stubborn girl who turned out to be the weakest monster in this maze!",
        genre: ["", "Detective", "Comedy", "Magic", "Adventures", "Fantasy", "Action"],
        rate: 6.5,
        age: "14+",
        year: 2021,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/606459fa9af72265580666.jpg",
        linkVideo: "https://www.youtube.com/embed/2hyDlt_yvv4",
    },
    //17
    {
        id: 17,
        title: "The daily life of an immortal King",
        description: "A young genius among wizards, the boy Wang Lin, was able to defeat a mighty demon at the age of 6. For the sake of his protection, it was decided not to advertise his abilities and give him the opportunity to live an ordinary life. Wang Lin is not ambitious, he is not attracted to fame, wealth, and the prospect of becoming a powerful magician, too.",
        genre: ["", "Demons", "Comedy", "Slice of life", "Adventures", "Fantasy", "School"],
        rate: 7.0,
        age: "0+",
        year: 2020,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5f00372c7a6ed536216626.jpg",
        linkVideo: "https://www.youtube.com/embed/ov3VnbKNepQ",
    },
    //18
    {
        id: 18,
        title: "The Misfit of Demon King Academy",
        description: "The cruel lord of darkness, defeated two thousand years ago, has been reborn... However, at the academy, where they teach candidates for the lords of darkness, he was rated… \"not fit\"?! He destroyed people, spirits and even gods, but the endless war bored him, and the lord of darkness, the Announcement of Voldigad, was reborn with a dream of a peaceful world. Only two thousand years later, his descendants, who were extremely weakened from peaceful life, and magic that had fallen into complete decay, were waiting for him.",
        genre: ["", "Demons", "Magic", "Fantasy", "School", "Action"],
        rate: 8.0,
        age: "14+",
        year: 2020,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5f1b1003f1428828153170.jpg",
        linkVideo: "https://www.youtube.com/embed/7tWLrGdk9ko",
    },
    //19
    {
        id: 19,
        title: "The Pet Girl of Sakurasou",
        description: "There are many dormitories at the Suimei University High School of Arts, and there is a Sakura apartment building. If strict rules apply in dormitories, then everything is possible in Sakura, no wonder its local nickname is \"madhouse\". Since genius and madness are always somewhere nearby in art, the inhabitants of the \"cherry orchard\" are talented and interesting guys who are too much out of the \"swamp\".",
        genre: ["", "Drama", "Comedy", "Slice of life", "Romance", "School"],
        rate: 8.0,
        age: "14+",
        year: 2012,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5f718b8bdaab3134220072.jpg",
        linkVideo: "https://www.youtube.com/embed/E3F6jKwMk78",
    },
    //20
    {
        id: 20,
        title: "Black Clover",
        description: "As infants, on the same day, Asta and Yuno were thrown under the doors of a church in a remote village. As the years passed, the boys grew up, and magic ruled the world around them. Yuno turned out to be a truly gifted magician, and Asta could not conjure even the simplest of spells. On their fifteenth birthday, the boys will receive their own spell book — a grimoire. Best friends in the past, and now rivals… They share the same dream for two. Each of them wants to become a Sorcerer King. And giving up is not about them!",
        genre: ["", "Comedy", "Magic", "Senen", "Fantasy", "Action"],
        rate: 8.0,
        age: "14+",
        year: 2017,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5bbd16801a7cd762823407.jpg",
        linkVideo: "https://www.youtube.com/embed/jYUQ1Px3zPA",
    },
    //21
    {
        id: 21,
        title: "Mieruko-chan",
        description: "The daily life of a high school student Miko changes dramatically when she awakens a sixth sense in herself and begins to see the souls of the dead and ghosts. She cannot stop seeing terrible, disgusting monsters and does not know the reason for the manifestation of these abilities. Despite the fact that Miko is very scared, she continues her everyday life as if nothing had happened and pretends not to notice the nightmare that surrounds her. Not to go crazy girl helps her best friend Hana. From this moment on, Miko will have to go through many difficulties and learn the details of the mysterious phenomena happening to her.",
        genre: ["", "Comedy", "Supernatural", "Horrors"],
        rate: 8.7,
        age: "14+",
        year: 2021,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/612fa8ab10633055514747.jpg",
        linkVideo: "https://www.youtube.com/embed/tzE5PxP34mk",
    },
    //22
    {
        id: 22,
        title: "Rascal Does Not Dream of Bunny Girl Senpai",
        description: "Azusagawa Sakura, sitting in an ordinary city library, encounters an incredibly mysterious and at the same time insanely attractive stranger. She dressed in a revealing bunny costume, which completely contradicts the surrounding environment. They have definitely not appeared in such outfits in the reading room yet. A strange person appears as Sakurajime Mai. She doesn't care at all what the crowd thinks and what library rules exist at all. The girl has a question much more important than the condemnation and grumbling of a local employee.",
        genre: ["", "Comedy", "Romance", "Supernatural", "School"],
        rate: 9.3,
        age: "14+",
        year: 2018,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5bd44a78177e0386016094.jpg",
        linkVideo: "https://www.youtube.com/embed/o0TZj_d3Yfg",
    },
    //23
    {
        id: 23,
        title: "Your Lie in April",
        description: "Kosei Arima is a virtuoso pianist, as his mentors said. From a young age, he played the most complex compositions thanks to his flair, he did everything exactly as prescribed in the notes, even mechanically. Having won a lot of competitions, experts still said that it was not talent, but discipline and perseverance, and the boy just quickly coped with the loads. Anyway, he was recognized as one of the best pianists in his category. When he turned 11, his mother, who was the main mentor, died. After this tragedy, the boy no longer approached the piano, he stopped feeling the music he was playing. He locks himself in his world, where there is only room for two old friends - Tsubaki and Ryota.",
        genre: ["", "Drama", "Music", "Romance", "Senen", "School"],
        rate: 9.2,
        age: "14+",
        year: 2014,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5c34be28c0d07340751757.jpg",
        linkVideo: "https://www.youtube.com/embed/aMJpI_fEsA4",
    },
    //24
    {
        id: 24,
        title: "Noragami",
        description: "Like a wandering Japanese god who recently lost absolutely everything. The main character has come down to earth and is trying to do everything possible to survive. It turns out that every divine creature needs people who believe in him. This adds an incredible amount of strength, but for that everything is too sad. He has no admirers and in addition he is thrown by Maya, who is his weapon. You have to hide from demons trying to kill anyone who gets in their way.",
        genre: ["", "Comedy", "Adventure", "Supernatural", "Senen", "Action"],
        rate: 8.9,
        age: "14+",
        year: 2014,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5a8b144777b57658716956.jpg",
        linkVideo: "https://www.youtube.com/embed/qx9ieoCsd1w",
    },
    //25
    {
        id: 25,
        title: "Cyberpunk: Edgerunners",
        description: "Night City is the city of the future, equipped with all kinds of the latest technologies. A city where body modification is not just the dreams of mad scientists, but the reality is akin to an ordinary purchase. It is there that our young hero lives, for whom this city is not something unimaginable, he knows all its real essence, where survival is not just a word, but the true face of this world. In an instant, having lost everything he had, the guy does not give up and in the struggle for survival becomes a mercenary nicknamed Cyberpunk.",
        genre: ["", "Fantasy", "Action"],
        rate: 9.3,
        age: "16+",
        year: 2022,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/6321e088d91c5890130687.jpg",
        linkVideo: "https://www.youtube.com/embed/x4ztgjvfU60",
    },
    //26
    {
        id: 26,
        title: "Boku dake ga Inai Machi",
        description: "An ordinary thirty-year-old young man, a loser in the life of Satoru Fujinuma. He is almost thirty, at this age many already run companies and add up good accounts, the hero counts the pennies received on pizza delivery and draws manga, in which he does not succeed. But everything is not simple, a nondescript guy has great abilities, he has a \"rebirth\". He has the ability to rewind the clock of time back and save someone from death. The gift can manifest itself at any time, but this does not prevent the guy from helping people, although sometimes it passes as a set of random events that leave injuries.",
        genre: ["", "Detective", "Psychological", "Supernatural", "Seinen"],
        rate: 8.0,
        age: "14+",
        year: 2016,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5a70aa46d6010.jpg",
        linkVideo: "https://www.youtube.com/embed/SUKevBJ703o",
    },
    //27
    {
        id: 27,
        title: "Grand Blue",
        description: "The storyline decides to show the audience an interesting story about the bright sun, a warm beach, fascinating landscapes and, of course, the company of cheerful friends who are not afraid to dive into the water surface and trust her with their own lives. Of course, diving is impossible to learn in a minute. To become a true professional, you need to train long and hard, and also not be afraid of depth at all. If there is no inner strength and a great desire, you can safely cross yourself off the list of experienced specialists.",
        genre: ["", "Comedy", "Slice of life", "Seinen"],
        rate: 9.5,
        age: "14+",
        year: 2018,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5bb095f7d0221321870491.jpg",
        linkVideo: "https://www.youtube.com/embed/5v2YYUbgbAg",
    },
    //28
    {
        id: 28,
        title: "Neon Genesis Evangelion",
        description: "Fifteen years have passed since a large-scale unexplained catastrophe hit the Earth. A huge number of people died during the chaos that reigned, and the lucky survivors could not even think that the terrible incident was just the beginning of a chain of trials. At some point, the planet was attacked by huge creatures called Angels. The weapons capable of giving a worthy rebuff to monsters were the combat robots of the Evangelion category, created by brilliant scientists with the help of modern technologies. But only individual pilots who were able to overcome the synchronization procedure with the Evangelion could control the unique biorobots.",
        genre: ["", "Madness", "Drama", "Furs", "Psychological", "Fantasy", "Action"],
        rate: 9.0,
        age: "14+",
        year: 1995,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/61805af1bbcd9937322084.jpg",
        linkVideo: "https://www.youtube.com/embed/13nSISwxrY4",
    },
    //29
    {
        id: 29,
        title: "Date A Live IV",
        description: "The human planet is being subjected to a powerful cosmic attack. The heavens are literally shaking with terrifying discharges. Soon unknown beings appear on Earth, which are called spirits. The occurrence of uninvited guests poses a serious threat to the existence of people. The government is urgently composing a plan aimed at creating a secret organization \"Rotatosk\". Community members are obliged to stop the rapid spread of aliens and protect innocent residents. Elementary romance becomes the method of effective struggle.",
        genre: ["", "Harem", "Comedy", "Furs", "Romance", "Fantasy", "School"],
        rate: 9.8,
        age: "16+",
        year: 2022,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/625048d38ff7f947610926.jpg",
        linkVideo: "https://www.youtube.com/embed/3v8AVVZSi9c?start=1",
    },
    //30
    {
        id: 30,
        title: "Date A Live III",
        description: "The human planet is being subjected to a powerful cosmic attack. The heavens are literally shaking with terrifying discharges. Soon unknown beings appear on Earth, which are called spirits. The occurrence of uninvited guests poses a serious threat to the existence of people. The government is urgently composing a plan aimed at creating a secret organization \"Rotatosk\". Community members are obliged to stop the rapid spread of aliens and protect innocent residents. Elementary romance becomes the method of effective struggle.",
        genre: ["", "Harem", "Comedy", "Furs", "Romance", "Fantasy", "School"],
        rate: 8.9,
        age: "16+",
        year: 2019,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/61d04c53ae058148245219.jpg",
        linkVideo: "https://www.youtube.com/embed/gHTqQSW_g4k?start=1",
    },
    //31
    {
        id: 31,
        title: "The Rising of the Shield Hero",
        description: "The dark forces have awakened and are ready to attack Malmark, a parallel universe in whose cities the sun is always shining and people are smiling in the streets. As the prophecy said, only four heroes are able to save the world from the destructive waves that are ready to destroy the entire population. The strength of ordinary warriors is gradually fading, they are close to defeat. In order to find the very heroes, the only ones who can overcome the evil spirits, the brave townspeople go to another dimension, where, presumably, the saviors can live. They hear the pleas and go to the engulfed city to save innocent and defenseless people. They are armed with arrows, swords and magical powers.",
        genre: ["", "Drama", "Comedy", "Adventure", "Romance", "Seinen", "Fantasy", "Action"],
        rate: 9.3,
        age: "14+",
        year: 2019,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5d03d83d33ba2222302542.jpg",
        linkVideo: "https://www.youtube.com/embed/jZvFEtR8RH0",
    },
    //32
    {
        id: 32,
        title: "The Rising of the Shield Hero Season 2",
        description: "A week remains until the start of the next Wave, and Naofumi's team does not waste a single minute in vain. However, when an attack begins on the village of Lurolona, time stops until the end of the Wave, and the four heroes gather again at Queen Mirelia Kew Melromark for a brief briefing on what happened. The Queen suggests that all these strange events are somehow connected with the Spirit of the Turtle - a dangerous creature that woke up from a dream and returned to wreak havoc and destruction again. It was decided to develop a plan to pacify the Spirit of the Turtle, but of the four famous heroes, only the cursed hero of the shield agrees to help.",
        genre: ["", "Drama", "Adventure", "Fantasy", "Action"],
        rate: 7.7,
        age: "14+",
        year: 2022,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/6249621ff25ff300710365.jpg",
        linkVideo: "https://www.youtube.com/embed/gocMuGq87lw",
    },
    //33
    {
        id: 33,
        title: "Naruto",
        description: "There is a world that is in no way similar to ours, modern and developing. This world is far from the stereotype that we are used to seeing every day when we get up for a painful job or study. In this \"unknown\" society for us, which is developing in a strange way, the distant Middle Ages, with its well-established laws and orders, with lords and merchants, is combined with strange people who call themselves \"ninja\", can sit on the couch and watch an old TV on weekends. Every ninja that lives in this world has conquered three great paths – the path of the body, illusion and hidden – taijutsu, ninjutsu and genjutsu. Each of the disciplines has unique features and special tasks.",
        genre: ["", "Martial arts", "Comedy", "Adventures", "Senen", "Superpower", "Action"],
        rate: 9.2,
        age: "16+",
        year: 2002,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5a3fbef2671f5.jpg",
        linkVideo: "https://www.youtube.com/embed/oJwMiU3RJmA",
    },
    //34
    {
        id: 34,
        title: "Code Geass: Hangyaku no Lelouch",
        description: "This anime will tell a story about a young Lelouch, who is the heir to the throne of the emperor. Because of the hard war, he lost his entire family, becoming an orphan. The narrative begins when Britain captures a third of the world, the homeland of Lelouch – Japan, becomes a small country, which is nicknamed \"Zone 13\". The boy, at the grave of his parents, makes a promise that he will avenge their death. One day, during one of the fights, the main character meets an unusual girl who introduces herself as S.S., she offers him a gift called \"Gias\" – the ability to subordinate the will of other people, just corresponding to his kind. And he decides to join the resistance. Now he will have to lead a double life – a student at his academy and a mysterious masked fighter in the war. Although it will not be easy for him, because his best friend, who has always supported, guided him on the right path, goes to the opposite side.",
        genre: ["", "Military", "Furs", "Superpower", "Fantasy", "School", "Action"],
        rate: 8.0,
        age: "18+",
        year: 2006,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5a736eff7b3ef.jpg",
        linkVideo: "https://www.youtube.com/embed/v-AGjx0N24U",
    },
    //35
    {
        id: 35,
        title: "Bleach: Thousand-Year Blood War",
        description: "The end is near. \"Gotei 13\" is under threat of complete destruction. The old powerful enemy of all Shinigami once again declares war on the Society of Souls. And this is none other than the Quincy themselves, led by the new emperor of Vandenreich, who calls himself Yahweh. And its purpose is as clear as the shine of a zanpakto blade. He wants to kill the King of Souls, seize the throne and build his new empire on the ruins. So the flame of a thousand-year bloody war is flaring up with renewed vigor, and the coming battle will shake both worlds and change the fate of many. How hard will this test be? Are they that good, these shinigami? And what can be the price of victory in a war once started? I'll have to find out the answer…",
        genre: ["", "Adventures", "Fantasy", "Action"],
        rate: 9.6,
        age: "18+",
        year: 2022,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/6325a97c596a5704160745.jpg",
        linkVideo: "https://www.youtube.com/embed/fzR82oXbjnY",
    },
    //36
    {
        id: 36,
        title: "Demon Slayer: Kimetsu no Yaiba Entertainment District Arc",
        description: "The continuation of the adventures of Tanjiro and his constant companions: the demon sister Nezuko, the ever-whining Zenitsu and the daredevil Inosuke. This time, the \"pillar of sound\" Tengen Uzui takes them with him on a mission to the Red Light District, where people have been disappearing lately. The reason for this is most likely demons. So who is behind all the disappearances, and will our heroes be able to cope with it?",
        genre: ["", "Demons", "Historical", "Supernatural", "Senen", "Action"],
        rate: 9.6,
        age: "18+",
        year: 2021,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/61c0e7650a79e589259475.jpg",
        linkVideo: "https://www.youtube.com/embed/Jd_B6ox3qGc",
    },
    //37
    {
        id: 37,
        title: "Date A Live II",
        description: "The invasion of the planet continues, but the earthlings are ready to strike back. Japanese schoolboy Shido Itsuka is the last hope of mankind, because only he has enough charm skills and destroys one alien after another. The fact is that in order to disguise themselves in the human world, they take the guise of cute girls. Just catching such takes a guy who has reached the highest level of seduction on the part of the enemy. Who needs machine guns and bombs now, when there is the power of love?",
        genre: ["", "Harem", "Comedy", "Furs", "Romance", "Fantasy", "School"],
        rate: 8.7,
        age: "16+",
        year: 2014,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5c380a9edf805553398339.jpg",
        linkVideo: "https://www.youtube.com/embed/bMpb1E016yY",
    },
    //38
    {
        id: 38,
        title: "Code Geass: Hangyaku no Lelouch R2",
        description: "One year has already passed since the events of the Black Uprising and the alleged death of Zero. Britain assigned Zone 11 the status of a penal colony, where the Eleventh were humiliated with the help of brute force and knocked out all thoughts of riots and attempts at a new uprising.",
        genre: ["", "Military", "Drama", "Furs", "Superpower", "Fantasy", "Action"],
        rate: 9.5,
        age: "18+",
        year: 2008,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5a743e804fcb8.jpg",
        linkVideo: "https://www.youtube.com/embed/KVqmEV3evbc",
    },
    //39
    {
        id: 39,
        title: "Horimiya",
        description: "Kyoko Hori, a high school student, seems to have everything you could wish for, because she is smart, beautiful and a favorite of the whole class. However, even seemingly perfect people have secrets, and Hori has one: the girl is terribly afraid that her classmates will find out that outside of school she turns into a real housewife, on whom parents who are always disappearing at work have thrown off all the household chores and her younger brother Sotu. One day, a stranger appears on her doorstep, holding the hand of an injured Sotu... and he also knows Hori! It immediately turns out that this guy is actually Hori's nondescript classmate, Miyamura. What will happen after the meeting of the popular beauty and the \"gray mouse\"? Friendship, love?.. Meet the school comedy full of the energy of youth!",
        genre: ["", "Comedy", "Slice of life", "Romance", "Senen", "School"],
        rate: 9.4,
        age: "18+",
        year: 2021,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5ff8de37e4d15498783235.jpg",
        linkVideo: "https://www.youtube.com/embed/e4RCugyx5No",
    },
    //40
    {
        id: 40,
        title: "Kaguya-sama: Love is War",
        description: "Leadership in the teenage sphere is of the greatest importance. It gives confidence and gives respect from peers. It is quite easy for guys with outstanding intelligence to get an attractive title. But the discharge of a certain genius does not guarantee that all the benefits will instantly fall at the feet of a teenager. In the famous Shuichi Academy, which belongs to prestigious institutions, quite capable boys and girls study. Almost everyone here is endowed with a unique gift. Although even in a \"brilliant\" company, there may be a truly unattainable person.",
        genre: ["", "Comedy", "Psychological", "Romance", "Seinen", "School"],
        rate: 9.1,
        age: "16+",
        year: 2019,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5c40382862d8a143640923.jpg",
        linkVideo: "https://www.youtube.com/embed/N4UH-kkVJpA",
    },
    // 41
    {
        id: 41,
        title: "Domestic na Kanojo",
        description: "Natsuo is a simple high school student who has long understood what kind of ladies attract him. The young man feels a genuine attraction to a charming person who is a little older than him. Hina is a teacher who does not notice the feelings of a young boyfriend. After a little thought , the boy agrees to spend the night with an enthusiastic Ru yi . After the completion of the process, the schoolgirl suddenly plunges into strong regrets, because she absolutely did not feel pleasant emotions. And the guy is now worried about an unwanted short-term affair. So both characters begin to suffer seriously.",
        genre: ["", "Drama", "Romance", "Senen", "School"],
        rate: 8.3,
        age: "16+",
        year: 2019,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5c3fa2f54e30c445057137.jpg",
        linkVideo: "https://www.youtube.com/embed/5WoZyCur8BM",
    },
    // 42
    {
        id: 42,
        title: "Love Me, Love Me Not",
        description: "Everyone talks about love in their own way. For Yuna, romance is above all, while Akari is too down-to-earth and practical in her views. But girls are girls. What about the guys? Those, it turns out, have not gone far from their friends. Kazuomi has a wind in her head, and the guy doesn't seem to know anything about love. But Rio does not waste time in vain and does not miss a single girl who confesses to him while she seems cute. Each of them talks about love in their own way. But the day will come when some of them will have to make a choice. Who will remain true to himself, and who will change his idea under the power of love? After all, she, as you know, changes people.",
        genre: ["", "Drama", "Romance", "Shojo", "School"],
        rate: 8.7,
        age: "14+",
        year: 2020,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/613f1fa8a5fee879574354.jpg",
        linkVideo: "https://www.youtube.com/embed/SjJc7TeKuus",
    },
    // 43
    {
        id: 43,
        title: "Kuroko's Basketball",
        description: "Tetsuya Kuroko finds himself in the Seirin Educational institution. He immediately signs up for a local team. Despite its relative youth, the institution has already managed to prove itself at the national tournament. Undoubtedly, the club was delighted that talented newcomers appeared in the ranks of athletes. Among the recruits was Taiga Kagami, a boy who studied in America. The not particularly noticeable young man was on the list of star players who regularly appeared on the grounds. But the information came only from his words. Believe him or not? Only time will show the real gift of a boastful guy, and, of course, the newfound comrades will appreciate it.",
        genre: ["", "Comedy", "Senen", "Sports", "School"],
        rate: 9.0,
        age: "16+",
        year: 2012,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5aca08af08caf111987219.jpg",
        linkVideo: "https://www.youtube.com/embed/5RVEM8-UKlg",
    },
    // 44
    {
        id: 44,
        title: "Kuroko's Basketball 2",
        description: "The Teiko High School basketball team has been a serious opponent for many teams for a long time. She was winning without giving the slightest chance of winning.\n" +
            "The \"Generation of Miracles\" are the five best geniuses of this team, who demonstrated an incredible level of play. With their help, Teiko was able to achieve the seemingly impossible. For three years in a row, she became the winner at the international basketball championship, not to mention various kinds of competitions.\n" +
            "But everything comes to an end sooner or later. And even such an incredibly strong and talented basketball team.\n" +
            "After graduation, everyone went to different high schools. The \"Generation of Miracles\" was no exception. Now each of them will have to rely on their own strength, not forgetting that former teammates have become a serious obstacle on the way to the international championship.\n" +
            "Tetsuya Kuroko, the \"ghost player\" of the famous Teiko, has already felt the increased power of the \"Generation of Miracles\". That's just that he and his team do not want to give up the goal so easily. Therefore, even tougher training became the first step for them to fight geniuses on equal terms.\n" +
            "This time everything will be decided at the \"Winter Cup\" competition. After all, a team worthy of being called the best will be determined there. And here our heroes should not forget about one more obstacle on their way: about the \"uncrowned kings\" — players who remained in the shadow of the \"Generation of Miracles\", but not much inferior to them. These guys can cause a lot of trouble.\n" +
            "Will our heroes be able to break through and achieve their goal by scattering rivals on the court? Anyone would say it's impossible. However, the elder Seirin has just started to gain momentum!",
        genre: ["", "Comedy", "Senen", "Sports", "School"],
        rate: 9.2,
        age: "16+",
        year: 2013,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5aca67b896fef801815500.jpg",
        linkVideo: "https://www.youtube.com/embed/ZYZSwzmgCTU",
    },
    // 45
    {
        id: 45,
        title: "Tower of God",
        description: "A mysterious force known as Shinsu has appeared in the world. And there is also a Tower — house for people who enjoy the benefits of Shinsu and call themselves \"the chosen ones\". They say that those who reach the top of the Tower will fulfill all their desires. To get to the top, the \"Chosen Ones\" selected by the keeper of the Tower are required to pass the tests… And together with them, Baam climbs the Tower — the main character and \"Illegal\", who opened the doors to himself. He does this with a single purpose - to find Rachel, who was everything to him.",
        genre: ["", "Detective", "Drama", "Adventure", "Fantasy", "Action"],
        rate: 8.9,
        age: "16+",
        year: 2020,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5e84cd60b6282406535190.jpg",
        linkVideo: "https://www.youtube.com/embed/JzK0k6MfvCc",
    },
    // 46
    {
        id: 46,
        title: "Gleipnir",
        description: "\"Why am I taking this form?\" Shuichi Kagaya is a young man with a dangerous ability for the whole world: he can transform into a strange animal costume. And one day his power attracts the attention of a mysterious girl named Claire ... Meeting her finally ruins Shuichi's peaceful life: monsters are hunting him — people with the same ability as the guy. Becoming one, Shuichi and Claire decide to fight for their fate. They are fighting for a \"coin\" that can cause a great cataclysm!",
        genre: ["", "Detective", "Supernatural", "Seinen", "Action", "Etty"],
        rate: 8.4,
        age: "18+",
        year: 2020,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5e8a99bb8cc6b055355644.jpg",
        linkVideo: "https://www.youtube.com/embed/bzTf3h08EYc",
    },
    // 47
    {
        id: 47,
        title: "Remake our Life!",
        description: "Keya Hasiba is a 28—year-old game developer. His company went bankrupt, he lost his job and returns to his hometown. He envies peers who have successfully settled in the industry, and falls asleep with sad thoughts. Waking up, the guy realizes that he was transported back ten years to the time when he entered the university. Will he be able to make the right decision?",
        genre: ["", "Drama", "Comedy", "Slice of life", "Romance"],
        rate: 8.8,
        age: "16+",
        year: 2021,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/60d375b3adad0038177523.jpg",
        linkVideo: "https://www.youtube.com/embed/8nwgtqF9huk",
    },
    // 48
    {
        id: 48,
        title: "Guilty Crown",
        description: "A seventeen–year-old boy, Xiu Oma, also joined the ranks of the \"defenders\". Together, the resistance units want to get a superweapon capable of stopping GHQ employees. Many difficulties fell on the shoulders of Xiu Om. He literally has to be in several places at the same time. Not only is the young man defending the state, he is trying to be good for Inori, the singer, because of his infatuation. And the boy has to attend school, because no one canceled lessons. Will the character last a long time with such tension, or will he decide to give up?",
        genre: ["", "Drama", "Furs", "Romance", "Superpower", "Fantasy", "Action"],
        rate: 8.4,
        age: "18+",
        year: 2011,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5ca5bddeaa291981771335.jpg",
        linkVideo: "https://www.youtube.com/embed/DjUtmbZt8zc",
    },
    // 49
    {
        id: 49,
        title: "Another",
        description: "More than 20 years ago, a kind and sociable girl named Misaki studied in this class. She died under unknown circumstances, and the details of those events are still unknown to anyone. For some reason, everyone around her denied her death, and since then the last seat of the left row in the 9th \"B\" class has remained unoccupied. However, the metropolitan guest did not know this story and first of all greeted a quiet girl with an eye patch. This caused shock to others, after which they became suspicious of the stranger. Koichi, trying to understand the reasons for what is happening, learned from his new friend that the whole point is that her name is Mei Misaki!",
        genre: ["", "Detective", "Supernatural", "Thriller", "Horrors", "School"],
        rate: 8.5,
        age: "18+",
        year: 2012,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/62b1898089fd3370117992.jpg",
        linkVideo: "https://www.youtube.com/embed/_U_57mzfjB4",
    },
    // 50
    {
        id: 50,
        title: "Seraph of the End: Vampire Reign",
        description: "They will be their \"food\", which will perfectly be able to support their life. The main character is a young guy named Yuichiro Hyakuya. He spent four whole years underground, and now he began to understand that this should not continue. Having gathered a group of brave people, he decides to get out of captivity and try to escape. To their great disappointment, they did not manage to get far and everyone was killed. Only Yuichiro survived, and he is going to do everything possible in an attempt to prevent the impending tragedy. Will he be able to stop the nightmare, or will he not be able to cope with the vampires alone?",
        genre: ["", "Vampires", "Drama", "Supernatural", "Senen", "Action"],
        rate: 8.7,
        age: "18+",
        year: 2015,
        img: "https://animego.org/media/cache/thumbs_250x350/upload/anime/images/5a8183f0e4d85285344092.jpg",
        linkVideo: "https://www.youtube.com/embed/NtzDAmRhD9s",
    },
    // {
    //     id: 41,
    //     title: "",
    //     description: "",
    //     genre: ["",],
    //     rate: 0,
    //     age: "",
    //     year: 1,
    //     img: "",
    //     linkVideo: "/",
    // },
];